### ISSUE TITLE
Cannot get the sniffer to work

### ISSUE THREAD

**Issue by scholi** [jmc265/node-red-contrib-rpi-433#6]
Hi and thank you for sharing the library. I somehow cannot use the sniffer.
I wired my rf433 device to raspberry pin 11, which is GPIO17 and equivalent to wirepi PIN 0.
I wired it in node red directly to a debug node using
pin: 0
pulse length: 350
debounce time: 500
Pushing a remote control doesn't output anything in node red. If I use `RFSniffer 0 0` from a command line I get a valid output giving me the code and a pulse length of either 358 or 359.
I understood that the second 0 is the pin number. What is the first zero ?

Here is the node-red code:
`[{"id":"b79c617e.2ab8d","type":"rpi-433-sniffer","z":"a50a4c3.bad5ab","pin":"0","pulseLength":"350","debounceDelay":"500","x":250,"y":280,"wires":[["4f2159fd.566e68"]]},{"id":"4f2159fd.566e68","type":"debug","z":"a50a4c3.bad5ab","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":430,"y":280,"wires":[]}]`

**Comment by jmc265** [comment]
The first 0 in `RFSniffer 0 0` is the pulse length attribute: https://github.com/jmc265/rpi-433-v3/blob/master/src/RFSniffer.cpp#L31

Do you have any further debug information? Is anything outputted in the node red logs? Is the RFSniffer command running when you look at your processes? 
A couple of things to check though:
* Does the user that node-red is running under have permission to access the GPIO pins?
* Are you running in docker? If so, I believe there are additional steps needed in order to give docker access to the GPIO pins.
